runtime: custom
env: flex

# Ensure we skip ".env", which is only for local development
skip_files:
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1
    cool_down_period_sec: 180
    cpu_utilization:
      target_utilization: 0.5

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

readiness_check:
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 5000
  path: "/_health"

env_variables:
    # Put production environment variables here.
    APP_DEBUG: true
    APP_ENV: production
    APP_KEY: base64:dqyLr8bPTwUZ7XjHawPFebLQpsRBbSvVZzE4M2yu5gY=
    APP_NAME: "GCP App - CODE"

    LOG_LEVEL: debug
