version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/mime.types:/etc/nginx/mime.types
      - ./etc/nginx/certs:/etc/nginx/certs
    depends_on:
      - web
      - db
    container_name: wj-nginx

  web:
    build: ./docker/web
    volumes:
      - .:/var/www/html
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db
    container_name: wj-web

  db:
    build: ./docker/mariadb
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - database-volume:/var/lib/mysql
    ports:
      - 3306:3306
    container_name: mysql

volumes:
  database-volume:
